apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy_edit
rules:
- apiGroups: ["","apps","extensions"]
  resources: ["pods","deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy_edit
subjects:
- kind: User
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
